
// @/app/admin/products/add/page.tsx
"use client";

import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ArrowLeft, PackagePlus, Save, UploadCloud, Loader2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import type { Product } from '@/types';
import { collection, addDoc } from "firebase/firestore";
import { db } from '@/lib/firebase';

type ProductFormData = Omit<Product, 'id'> & { // id will be auto-generated by Firestore
  sizes: string; // Comma-separated string from form
  colors?: string; // Comma-separated string from form
  tags?: string; // Comma-separated string from form
  // images field is for additional comma-separated URLs, imageUrl is for the uploaded main image
};

const initialFormData: ProductFormData = {
  name: '',
  price: 0,
  originalPrice: undefined,
  imageUrl: '', // This will hold the data URI of the uploaded image
  images: [], // For additional comma-separated URLs (will be parsed into array)
  description: '',
  sizes: '', // Will be parsed into string[]
  colors: '', // Will be parsed into string[]
  category: '',
  brand: '',
  stock: 0,
  tags: '', // Will be parsed into string[]
  sku: '',
  dataAiHint: '',
  averageRating: 0, // Default value
  reviewCount: 0,   // Default value
  reviews: [],      // Default value
};


export default function AddProductPage() {
  const [formData, setFormData] = useState<ProductFormData>(initialFormData);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { toast } = useToast();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;

    if (name === 'imageFile' && e.target instanceof HTMLInputElement && e.target.files?.[0]) {
      const file = e.target.files[0];
      if (file) {
        const reader = new FileReader();
        reader.onloadend = () => {
          const dataUrl = reader.result as string;
          setImagePreview(dataUrl);
          setFormData(prev => ({
            ...prev,
            imageUrl: dataUrl, 
            dataAiHint: prev.dataAiHint || file.name.split('.')[0].substring(0, 20).replace(/[^a-zA-Z0-9 ]/g, "") || "product",
          }));
        };
        reader.readAsDataURL(file);
      }
    } else {
      setFormData(prev => ({
        ...prev,
        [name]: name === 'price' || name === 'originalPrice' || name === 'stock' ? parseFloat(value) || (name === 'originalPrice' ? undefined : 0) : value,
      }));
    }
  };
  
  const handleAdditionalImagesChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
     // Assuming formData.images is a string of comma-separated URLs from input
     // but should be stored as string[] in ProductFormData.
     // The actual transformation to string[] happens in handleSubmit.
    setFormData(prev => ({
      ...prev,
      [name]: value, // Keep as string for input, parse on submit
    }));
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsSubmitting(true);
    
    if (!formData.imageUrl && !imagePreview) { // Check imagePreview if imageUrl isn't set yet by async filereader
      toast({
        title: "Image Required",
        description: "Please upload a main product image.",
        variant: "destructive",
      });
      setIsSubmitting(false);
      return;
    }
    
    let finalImagesArray: string[] = [];
    if (formData.imageUrl) { // Main uploaded image (data URI)
      finalImagesArray.push(formData.imageUrl);
    }
    // formData.images is a comma-separated string from the input field
    if (typeof formData.images === 'string' && formData.images.trim() !== '') { 
      const additionalImageUrls = formData.images.split(',').map(s => s.trim()).filter(s => s);
      finalImagesArray = [...finalImagesArray, ...additionalImageUrls];
    }


    const productDataToSave: Omit<Product, 'id'> = {
      ...formData,
      price: Number(formData.price),
      originalPrice: formData.originalPrice ? Number(formData.originalPrice) : undefined,
      stock: Number(formData.stock),
      sizes: formData.sizes.split(',').map(s => s.trim()).filter(s => s),
      colors: formData.colors?.split(',').map(s => s.trim()).filter(s => s) || [],
      tags: formData.tags?.split(',').map(s => s.trim()).filter(s => s) || [],
      images: finalImagesArray.length > 0 ? finalImagesArray : (formData.imageUrl ? [formData.imageUrl] : []),
      // averageRating, reviewCount, reviews are already defaulted in initialFormData
      averageRating: formData.averageRating || 0,
      reviewCount: formData.reviewCount || 0,
      reviews: formData.reviews || [],
    };
    

    try {
      const docRef = await addDoc(collection(db, "products"), productDataToSave);
      toast({
        title: "Product Added Successfully!",
        description: `${productDataToSave.name} has been saved with ID: ${docRef.id}.`,
        duration: 7000,
      });
      setFormData(initialFormData);
      setImagePreview(null);
      const imageInput = document.getElementById('imageFile') as HTMLInputElement;
      if (imageInput) {
          imageInput.value = ''; 
      }

    } catch (error) {
      console.error("Error adding document: ", error);
      toast({
        title: "Error Saving Product",
        description: "There was an issue saving the product. Check console.",
        variant: "destructive",
        duration: 7000,
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="container mx-auto max-w-screen-lg px-4 sm:px-6 lg:px-8 py-12 md:py-16">
      <div className="mb-8">
        <Button variant="outline" size="sm" asChild className="mb-4">
          <Link href="/admin/dashboard">
            <ArrowLeft className="mr-2 h-4 w-4" /> Back to Dashboard
          </Link>
        </Button>
        <div className="flex items-center gap-3">
            <PackagePlus className="h-10 w-10 text-primary" />
            <div>
                <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight text-foreground">Add New Product</h1>
                <p className="mt-1 text-md text-muted-foreground">Fill in the details for the new product.</p>
            </div>
        </div>
      </div>

      <Card className="shadow-xl border-border/60">
        <CardHeader>
          <CardTitle>Product Information</CardTitle>
          <CardDescription>Enter all necessary details. Upload a main image. Additional images can be URLs.</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <Label htmlFor="name">Product Name</Label>
                <Input id="name" name="name" value={formData.name} onChange={handleChange} placeholder="e.g., Classic Oxford Shirt" required className="text-base h-11"/>
              </div>
              <div className="space-y-2">
                <Label htmlFor="brand">Brand</Label>
                <Input id="brand" name="brand" value={formData.brand} onChange={handleChange} placeholder="e.g., Club Essentials" className="text-base h-11"/>
              </div>
            </div>
            
            <div className="space-y-2">
                <Label htmlFor="description">Description</Label>
                <Textarea id="description" name="description" value={formData.description} onChange={handleChange} placeholder="Detailed product description..." required rows={5} className="text-base"/>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="space-y-2">
                <Label htmlFor="price">Price (₹)</Label>
                <Input id="price" name="price" type="number" value={formData.price} onChange={handleChange} placeholder="e.g., 2999.00" required step="0.01" className="text-base h-11"/>
              </div>
              <div className="space-y-2">
                <Label htmlFor="originalPrice">Original Price (₹, Optional)</Label>
                <Input id="originalPrice" name="originalPrice" type="number" value={formData.originalPrice || ''} onChange={handleChange} placeholder="e.g., 3999.00" step="0.01" className="text-base h-11"/>
              </div>
               <div className="space-y-2">
                <Label htmlFor="stock">Stock Quantity</Label>
                <Input id="stock" name="stock" type="number" value={formData.stock} onChange={handleChange} placeholder="e.g., 50" required className="text-base h-11"/>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <Label htmlFor="category">Category</Label>
                <Input id="category" name="category" value={formData.category} onChange={handleChange} placeholder="e.g., Shirts, Trousers" className="text-base h-11"/>
              </div>
              <div className="space-y-2">
                <Label htmlFor="sku">SKU</Label>
                <Input id="sku" name="sku" value={formData.sku} onChange={handleChange} placeholder="e.g., MENS-OXF-001" className="text-base h-11"/>
              </div>
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="imageFile">Main Product Image</Label>
              <div className="flex items-center gap-4">
                <Input 
                  id="imageFile" 
                  name="imageFile" 
                  type="file" 
                  accept="image/*" 
                  onChange={handleChange} 
                  required={!imagePreview} // Required if no image is previewed yet
                  className="text-base h-11 flex-grow file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-primary/10 file:text-primary hover:file:bg-primary/20"
                />
                <UploadCloud className="h-6 w-6 text-muted-foreground"/>
              </div>
              {imagePreview && (
                <div className="mt-4 p-2 border border-dashed border-border rounded-md inline-block">
                  <Image
                    src={imagePreview}
                    alt="Product Preview"
                    width={200}
                    height={266} 
                    className="object-contain rounded-md"
                  />
                </div>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="images">Additional Image URLs (comma-separated, optional)</Label>
              <Input 
                id="images" 
                name="images" 
                value={typeof formData.images === 'string' ? formData.images : ''} // Ensure value is string for input
                onChange={handleAdditionalImagesChange}
                placeholder="url1.png, url2.png, ..." 
                className="text-base h-11"
              />
              <p className="text-xs text-muted-foreground">Externally hosted image URLs. Main image is uploaded above.</p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                    <Label htmlFor="sizes">Sizes (comma-separated)</Label>
                    <Input id="sizes" name="sizes" value={formData.sizes} onChange={handleChange} placeholder="S, M, L, XL" required className="text-base h-11"/>
                </div>
                <div className="space-y-2">
                    <Label htmlFor="colors">Colors (comma-separated, Optional)</Label>
                    <Input id="colors" name="colors" value={formData.colors || ''} onChange={handleChange} placeholder="White, Blue, Black" className="text-base h-11"/>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                    <Label htmlFor="tags">Tags (comma-separated, Optional)</Label>
                    <Input id="tags" name="tags" value={formData.tags || ''} onChange={handleChange} placeholder="formal, cotton, new arrival" className="text-base h-11"/>
                </div>
                <div className="space-y-2">
                    <Label htmlFor="dataAiHint">AI Hint for Main Image (auto-filled, or custom)</Label>
                    <Input id="dataAiHint" name="dataAiHint" value={formData.dataAiHint || ''} onChange={handleChange} placeholder="e.g., men shirt" className="text-base h-11"/>
                     <p className="text-xs text-muted-foreground">Used for image search if placeholders are needed. Max 2 words.</p>
                </div>
            </div>

            <div className="flex justify-end pt-4">
              <Button type="submit" size="lg" className="text-base" disabled={isSubmitting}>
                {isSubmitting ? (
                  <>
                    <Loader2 className="mr-2 h-5 w-5 animate-spin" /> Saving...
                  </>
                ) : (
                  <>
                    <Save className="mr-2 h-5 w-5" /> Save Product
                  </>
                )}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
      <p className="mt-8 text-sm text-muted-foreground text-center">
        Products are saved to Firebase Firestore. 
        <br />
        <strong>Note on Images:</strong> Main image stored as data URI. For production, use Firebase Storage.
      </p>
    </div>
  );
}
